version: "3.7"

services:
  can_to_ip:
    depends_on:
      - can-mapping
    container_name: can_to_ip
    image: tobiasbohnen/de.thk.scooterfusion.mainboard.can_to_ip:latest
    restart: unless-stopped
    network_mode: "host"
  ip_to_can:
    depends_on:
      - can-mapping
    container_name: ip_to_can
    image: tobiasbohnen/de.thk.scooterfusion.mainboard.ip_to_can:latest
    restart: unless-stopped
    network_mode: "host"
  can-mapping:
    container_name: can-mapping
    image: tobiasbohnen/de.thk.scooterfusion.mainboard.can.api:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      scooterfusion-network:
        ipv4_address: "172.20.128.2"
networks:
  scooterfusion-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
